library(igraph)
traffic.graph <- graph.empty(n=0)

traffic.graph <- traffic.graph + vertex("Universidad de Granada 2")
traffic.graph <- traffic.graph + vertex("Sipesca 12 bluetooth La Rinconada")
traffic.graph <- traffic.graph + vertex("Sipesca 5 wifi Alcalá del Río")
traffic.graph <- traffic.graph + vertex("Sipesca 2 bluetooth Los Rosales")
traffic.graph <- traffic.graph + vertex("Sipesca 12 wifi La Rinconada")
traffic.graph <- traffic.graph + vertex("Sipesca 3 bluetooth Guillena")
traffic.graph <- traffic.graph + vertex("Sipesca 2 wifi Los Rosales")
traffic.graph <- traffic.graph + vertex("Universidad de Granada 6")
traffic.graph <- traffic.graph + vertex("Sipesca 10 bluetooth A-8005")
traffic.graph <- traffic.graph + vertex("Sipesca 8 wifi La Algaba")
traffic.graph <- traffic.graph + vertex("Sipesca 11 wifi Carmona")
traffic.graph <- traffic.graph + vertex("Sipesca 4 bluetooth Torre de la Reina")
traffic.graph <- traffic.graph + vertex("Sipesca 9 bluetooth Burguillos")
traffic.graph <- traffic.graph + vertex("Sipesca 9 wifi Burguillos")
traffic.graph <- traffic.graph + vertex("Universidad de Granada 3")
traffic.graph <- traffic.graph + vertex("Universidad de Granada 5")
traffic.graph <- traffic.graph + vertex("Sipesca 10 wifi A-8005")
traffic.graph <- traffic.graph + vertex("Sipesca 5 bluetooth Alcalá del Río")
traffic.graph <- traffic.graph + vertex("Sipesca 1 wifi Brenes")
traffic.graph <- traffic.graph + vertex("Sipesca 8 bluetooth La Algaba")
traffic.graph <- traffic.graph + vertex("Universidad de Granada 4")
traffic.graph <- traffic.graph + vertex("Universidad de Granada 1")
traffic.graph <- traffic.graph + vertex("Sipesca 4 wifi Torre de la Reina")
traffic.graph <- traffic.graph + vertex("Sipesca 13 wifi San José")
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 9 wifi Burguillos",weight=77)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 13 wifi San José",weight=1084)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 4 wifi Torre de la Reina",weight=72)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 11 wifi Carmona",weight=51)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 8 wifi La Algaba",weight=99)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 10 wifi A-8005",weight=92)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 2 wifi Los Rosales",weight=188)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 12 wifi La Rinconada",weight=142)
traffic.graph <- traffic.graph + edge("Sipesca 1 wifi Brenes","Sipesca 5 wifi Alcalá del Río",weight=119)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Sipesca 3 bluetooth Guillena",weight=5)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Sipesca 4 bluetooth Torre de la Reina",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Universidad de Granada 6",weight=3103)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Universidad de Granada 5",weight=1456)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Sipesca 10 bluetooth A-8005",weight=1)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Sipesca 2 bluetooth Los Rosales",weight=4)
traffic.graph <- traffic.graph + edge("Universidad de Granada 4","Sipesca 12 bluetooth La Rinconada",weight=6)
traffic.graph <- traffic.graph + edge("Sipesca 8 bluetooth La Algaba","Sipesca 12 bluetooth La Rinconada",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 8 bluetooth La Algaba","Sipesca 10 bluetooth A-8005",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 12 wifi La Rinconada",weight=95)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 10 wifi A-8005",weight=47)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 9 wifi Burguillos",weight=33)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 13 wifi San José",weight=145)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 8 wifi La Algaba",weight=383)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 11 wifi Carmona",weight=4)
traffic.graph <- traffic.graph + edge("Sipesca 4 wifi Torre de la Reina","Sipesca 5 wifi Alcalá del Río",weight=58)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Sipesca 4 bluetooth Torre de la Reina",weight=4)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Sipesca 10 bluetooth A-8005",weight=1)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Universidad de Granada 4",weight=889)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Sipesca 3 bluetooth Guillena",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Universidad de Granada 5",weight=83)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Universidad de Granada 6",weight=270)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Universidad de Granada 2",weight=1060)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Universidad de Granada 3",weight=789)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Sipesca 12 bluetooth La Rinconada",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 1","Sipesca 2 bluetooth Los Rosales",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Sipesca 4 bluetooth Torre de la Reina",weight=3)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Universidad de Granada 4",weight=11112)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Sipesca 10 bluetooth A-8005",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Universidad de Granada 6",weight=5675)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Universidad de Granada 5",weight=1993)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Sipesca 3 bluetooth Guillena",weight=6)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Sipesca 12 bluetooth La Rinconada",weight=7)
traffic.graph <- traffic.graph + edge("Universidad de Granada 3","Sipesca 2 bluetooth Los Rosales",weight=6)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Sipesca 2 bluetooth Los Rosales",weight=4)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Sipesca 12 bluetooth La Rinconada",weight=6)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Sipesca 10 bluetooth A-8005",weight=1)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Universidad de Granada 6",weight=1896)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Sipesca 3 bluetooth Guillena",weight=4)
traffic.graph <- traffic.graph + edge("Universidad de Granada 5","Sipesca 4 bluetooth Torre de la Reina",weight=4)
traffic.graph <- traffic.graph + edge("Sipesca 10 wifi A-8005","Sipesca 11 wifi Carmona",weight=19)
traffic.graph <- traffic.graph + edge("Sipesca 10 wifi A-8005","Sipesca 12 wifi La Rinconada",weight=128)
traffic.graph <- traffic.graph + edge("Sipesca 10 wifi A-8005","Sipesca 13 wifi San José",weight=267)
traffic.graph <- traffic.graph + edge("Sipesca 5 bluetooth Alcalá del Río","Sipesca 9 bluetooth Burguillos",weight=8)
traffic.graph <- traffic.graph + edge("Sipesca 5 bluetooth Alcalá del Río","Sipesca 8 bluetooth La Algaba",weight=1)
traffic.graph <- traffic.graph + edge("Sipesca 5 bluetooth Alcalá del Río","Sipesca 12 bluetooth La Rinconada",weight=20)
traffic.graph <- traffic.graph + edge("Sipesca 5 bluetooth Alcalá del Río","Sipesca 10 bluetooth A-8005",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 8 wifi La Algaba","Sipesca 11 wifi Carmona",weight=9)
traffic.graph <- traffic.graph + edge("Sipesca 8 wifi La Algaba","Sipesca 12 wifi La Rinconada",weight=176)
traffic.graph <- traffic.graph + edge("Sipesca 8 wifi La Algaba","Sipesca 9 wifi Burguillos",weight=75)
traffic.graph <- traffic.graph + edge("Sipesca 8 wifi La Algaba","Sipesca 10 wifi A-8005",weight=102)
traffic.graph <- traffic.graph + edge("Sipesca 8 wifi La Algaba","Sipesca 13 wifi San José",weight=342)
traffic.graph <- traffic.graph + edge("Sipesca 10 bluetooth A-8005","Sipesca 12 bluetooth La Rinconada",weight=18)
traffic.graph <- traffic.graph + edge("Sipesca 11 wifi Carmona","Sipesca 12 wifi La Rinconada",weight=7)
traffic.graph <- traffic.graph + edge("Sipesca 11 wifi Carmona","Sipesca 13 wifi San José",weight=27)
traffic.graph <- traffic.graph + edge("Sipesca 4 bluetooth Torre de la Reina","Sipesca 5 bluetooth Alcalá del Río",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 4 bluetooth Torre de la Reina","Sipesca 9 bluetooth Burguillos",weight=4)
traffic.graph <- traffic.graph + edge("Sipesca 4 bluetooth Torre de la Reina","Sipesca 10 bluetooth A-8005",weight=5)
traffic.graph <- traffic.graph + edge("Sipesca 4 bluetooth Torre de la Reina","Sipesca 12 bluetooth La Rinconada",weight=15)
traffic.graph <- traffic.graph + edge("Sipesca 4 bluetooth Torre de la Reina","Sipesca 8 bluetooth La Algaba",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 9 wifi Burguillos","Sipesca 11 wifi Carmona",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 9 wifi Burguillos","Sipesca 13 wifi San José",weight=103)
traffic.graph <- traffic.graph + edge("Sipesca 9 wifi Burguillos","Sipesca 10 wifi A-8005",weight=21)
traffic.graph <- traffic.graph + edge("Sipesca 9 wifi Burguillos","Sipesca 12 wifi La Rinconada",weight=231)
traffic.graph <- traffic.graph + edge("Sipesca 9 bluetooth Burguillos","Sipesca 12 bluetooth La Rinconada",weight=36)
traffic.graph <- traffic.graph + edge("Sipesca 9 bluetooth Burguillos","Sipesca 10 bluetooth A-8005",weight=1)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Universidad de Granada 3",weight=6552)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Sipesca 2 bluetooth Los Rosales",weight=6)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Sipesca 12 bluetooth La Rinconada",weight=10)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Sipesca 3 bluetooth Guillena",weight=8)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Universidad de Granada 5",weight=1244)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Universidad de Granada 6",weight=2418)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Sipesca 10 bluetooth A-8005",weight=2)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Universidad de Granada 4",weight=6423)
traffic.graph <- traffic.graph + edge("Universidad de Granada 2","Sipesca 4 bluetooth Torre de la Reina",weight=6)
traffic.graph <- traffic.graph + edge("Sipesca 2 bluetooth Los Rosales","Sipesca 3 bluetooth Guillena",weight=7)
traffic.graph <- traffic.graph + edge("Sipesca 2 bluetooth Los Rosales","Sipesca 4 bluetooth Torre de la Reina",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 2 bluetooth Los Rosales","Sipesca 5 bluetooth Alcalá del Río",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 2 bluetooth Los Rosales","Sipesca 10 bluetooth A-8005",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 2 bluetooth Los Rosales","Sipesca 12 bluetooth La Rinconada",weight=13)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 12 wifi La Rinconada",weight=329)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 9 wifi Burguillos",weight=237)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 10 wifi A-8005",weight=38)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 13 wifi San José",weight=187)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 8 wifi La Algaba",weight=138)
traffic.graph <- traffic.graph + edge("Sipesca 5 wifi Alcalá del Río","Sipesca 11 wifi Carmona",weight=7)
traffic.graph <- traffic.graph + edge("Sipesca 12 wifi La Rinconada","Sipesca 13 wifi San José",weight=514)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 4 bluetooth Torre de la Reina",weight=22)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 9 bluetooth Burguillos",weight=12)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 5 bluetooth Alcalá del Río",weight=1)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 10 bluetooth A-8005",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 8 bluetooth La Algaba",weight=3)
traffic.graph <- traffic.graph + edge("Sipesca 3 bluetooth Guillena","Sipesca 12 bluetooth La Rinconada",weight=32)
traffic.graph <- traffic.graph + edge("Universidad de Granada 6","Sipesca 4 bluetooth Torre de la Reina",weight=4)
traffic.graph <- traffic.graph + edge("Universidad de Granada 6","Sipesca 3 bluetooth Guillena",weight=7)
traffic.graph <- traffic.graph + edge("Universidad de Granada 6","Sipesca 2 bluetooth Los Rosales",weight=8)
traffic.graph <- traffic.graph + edge("Universidad de Granada 6","Sipesca 12 bluetooth La Rinconada",weight=8)
traffic.graph <- traffic.graph + edge("Universidad de Granada 6","Sipesca 10 bluetooth A-8005",weight=2)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 11 wifi Carmona",weight=153)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 8 wifi La Algaba",weight=32)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 9 wifi Burguillos",weight=16)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 13 wifi San José",weight=117)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 4 wifi Torre de la Reina",weight=15)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 5 wifi Alcalá del Río",weight=23)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 10 wifi A-8005",weight=83)
traffic.graph <- traffic.graph + edge("Sipesca 2 wifi Los Rosales","Sipesca 12 wifi La Rinconada",weight=29)
plot(traffic.graph, layout = layout.fruchterman.reingold,
      vertex.size = 10,
      vertex.color="gray",
      vertex.frame.color= "white",
      vertex.label.color = "blue",
      vertex.label.family = "sans",
      edge.width=log(E(traffic.graph)$weight),  
      edge.color="black")

